Forgot Password
GSG-G7/mental-snapp pull request #71
Opened 2019-10-29 12:47 UTC by yosefalnajjarofficial

#14

2019-10-31 08:16 UTC, fares98 requested changes

2019-10-31 08:16 UTC, fares98 commented on src/containers/ForgotPassword/index.js
const index = () => <ForgotPassword />;

2019-10-31 08:25 UTC, fares98 submitted a review, later dismissed

2019-10-31 19:07 UTC, Fatmasiam commented
please write a description for **WHAT** the _page do_ ,**Not** what you are done

2019-10-31 19:11 UTC, Fatmasiam commented
Check the accessibility
---- 
![Screenshot from 2019-10-31 21-08-48](https://user-images.githubusercontent.com/37935654/67978494-e609cb80-fc22-11e9-9c6a-d6b49b16fdfc.png)

2019-10-31 19:12 UTC, Fatmasiam commented
**WHY** the page scrolling up and down ?!

2019-10-31 19:12 UTC, Fatmasiam commented on src/containers/ForgotPassword/index.js
> +  // eslint-disable-next-line react/state-in-constructor
eslint-disable-next-line !!!! 
**WHY**

2019-10-31 19:12 UTC, Fatmasiam commented on src/routes/App/style.css
> +@import url('https://fonts.googleapis.com/css?family=Poppins:400,500,700&display=swap');
you can import both fonts in the same URL 
---
```suggestion
@import url('https://fonts.googleapis.com/css?family=Open+Sans:300,400,600,700|Poppins:300,400,500,700&display=swap');
```

2019-10-31 19:12 UTC, Fatmasiam commented on src/containers/ForgotPassword/index.js
> +import ForgotPassword from './forgotPass';
add a broken line between the module import and local module.
---
The best ordering for the import is :
1. standard library modules — e.g.`react`
    * `add a broken line then point 2--> `
2. third-party library modules (anything installed) — e.g.`yup`, `react-router-dom`, etc.
    * `add a broken line then point 3-->` 
3. locally-developed modules( our file that we working on it )

2019-10-31 19:12 UTC, Fatmasiam commented on src/containers/ForgotPassword/forgotPass.css
> +}
repeated style !!! 
from line 74 to 76, and 81 to 83

2019-10-31 19:12 UTC, Fatmasiam commented on src/containers/ForgotPassword/forgotPass.css
> +  width: 80%;
repeated ` width:80%` ?!  and line 50

2019-10-31 19:23 UTC, Fatmasiam commented on src/containers/ForgotPassword/utils/schema.js
> +import * as yup from 'yup';
move the utils folder to the `src/` folder  root

2019-10-31 19:23 UTC, Fatmasiam commented on src/containers/ForgotPassword/vector.svg
> +<svg width="212" height="157" viewBox="0 0 212 157" fill="none" xmlns="http://www.w3.org/2000/svg">
move the `svg` image to the `assets/images/ ` folder

2019-10-31 19:23 UTC, Fatmasiam commented on src/containers/ForgotPassword/index.js
> +    // Logic will be added hereW
```suggestion
    // Logic will be added here
```
it's will be good if you write a cleaner comment like: make a  fetch to firebase server :smiley:

2019-10-31 19:27 UTC, Fatmasiam commented on src/containers/ForgotPassword/index.js
> +    const { ...props } = this.props;
unnecessary line 
```suggestion
```

2019-10-31 19:27 UTC, Fatmasiam commented on src/containers/ForgotPassword/index.js
> +        {...props}
```suggestion
        {...this.props}
```

2019-10-31 19:33 UTC, Fatmasiam commented on src/containers/ForgotPassword/index.js
> +        this.setState({ error: 'the input is not a valid email' });
```suggestion
        this.setState({ error: 'Please, enter valid email ' });
```

2019-11-02 16:27 UTC, AlaaTaima submitted a review, later dismissed

2019-11-02 20:52 UTC, fares98 submitted a review, later dismissed

2019-11-03 20:05 UTC, fares98 requested changes

2019-11-03 20:05 UTC, fares98 commented on src/containers/ForgotPassword/index.js
>  import React from 'react';
remove this line

2019-11-04 12:05 UTC, fares98 requested changes

2019-11-04 12:05 UTC, fares98 commented on src/containers/ForgotPassword/forgotPass.jsx
> +      </header>
Use the Header component

2019-11-04 12:10 UTC, fares98 requested changes

2019-11-04 12:10 UTC, fares98 commented on src/containers/ForgotPassword/forgotPass.jsx
> +      </header>
Use the header component

2019-11-04 12:27 UTC, Fatmasiam submitted a review, later dismissed

2019-11-04 12:41 UTC, Fatmasiam commented on src/components/Header/header.css
> +  transform: translateX(-40%);
```suggestion
  transform: translateX(-58%);
```

2019-11-04 12:42 UTC, Fatmasiam approved these changes

2019-11-04 12:43 UTC, AlaaTaima approved these changes

2019-11-04 12:45 UTC, fares98 approved these changes

2019-11-04 12:48 UTC, alaa-yasin approved these changes

2019-11-04 12:50 UTC, merged