20 sign in
GSG-G7/mental-snapp pull request #88
Opened 2019-11-05 07:13 UTC by alaa-yasin

2019-11-05 07:30 UTC, Fatmasiam commented
where is the PR description ! and relates!

2019-11-05 07:33 UTC, Fatmasiam commented
fix the page style

2019-11-05 07:44 UTC, Fatmasiam commented on .storybook/config.js
> +<<<<<<< HEAD
conflict!

2019-11-05 07:44 UTC, Fatmasiam commented on src/containers/SignIn/index.js
> +        // eslint-disable-next-line no-console
disable eslint !

2019-11-05 07:44 UTC, Fatmasiam commented on src/containers/SignIn/index.js
> +                    /^(?=.*[A-Za-z])(?=.*\d)[A-Za-z\d].{8,}$/
we don't need the regex here ?!! 
in the sign-in we just need it to be required

2019-11-05 07:44 UTC, Fatmasiam commented on src/containers/SignIn/utils/signInSchema.js
> +import * as yup from 'yup';
i think we don't need this file

2019-11-05 07:45 UTC, Fatmasiam commented on src/containers/SignIn/signIn.css
> +}
add new line

2019-11-06 07:02 UTC, fares98 requested changes

2019-11-06 07:02 UTC, fares98 commented on src/containers/SignIn/index.js
> +    form: { getFieldDecorator, validateFieldsAndScroll },
use validateFields insted of validateFieldsAndScroll

2019-11-06 07:02 UTC, fares98 commented on src/containers/SignIn/index.js
> +          <Form.Item hasFeedback></Form.Item>
remove this line

2019-11-06 07:02 UTC, fares98 commented on src/containers/SignIn/index.js
> +          <Form.Item>
this element is not important

2019-11-06 14:16 UTC, fares98 approved these changes

2019-11-06 19:15 UTC, AlaaTaima approved these changes

2019-11-06 22:29 UTC, Fatmasiam approved these changes

2019-11-06 22:34 UTC, Fatmasiam approved these changes

2019-11-07 06:45 UTC, yosefanajjar approved these changes

2019-11-07 07:35 UTC, merged